name: Continuous Integration

# Trigger the CI pipeline on push or pull request (development branch)
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_call:

jobs:
  node-application-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Lint the Project
        run: npm run lint
      - name: Build the Project
        run: npm run build
      # Yeah, this repository doesn't have any tests yet XD.
      # It was just supposed to be a small project, I swear.
      #- name: Run Tests
      #  run: npm test
